steps:
  - label: "build-deps-x86"
    commands:
      - resources/kernel/make_busybox.sh -j 2
      - resources/kernel/make_busybox.sh -h -j 2
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
      os: linux
    plugins:
      - docker#v3.0.1:
          image: "rustvmm/dev:v7"
          always-pull: true
          volumes:
            - "/tmp:/tmp"
