steps:
  - label: "build-resources-x86"
    commands:
      - resources/make_test_resources.sh
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
      os: linux
    plugins:
      - docker#v3.0.1:
          image: "rustvmm/dev:v9"
          always-pull: true
          volumes:
            - "/tmp:/tmp"
          privileged: true
