[package]
name = "api"
version = "0.1.0"
authors = ["rust-vmm AWS maintainers <rust-vmm-maintainers@amazon.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
log = "0.4.14"
simple_logger = "1.11.0"

vmm = { path = "../vmm" }
