#!/bin/bash

# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

# This hook copies the kernel image(s) used in the integration tests from /tmp.

RESDIR="resources/kernel"
WORKDIR="/tmp/vmlinux_busybox"
KERNEL="linux-4.14.176"
KERNEL_BINS=(
    "vmlinux-hello-busybox"
    "vmlinux-hello-busybox-halt"
    "bzimage-hello-busybox"
    "bzimage-hello-busybox-halt"
)

arch=$(dpkg --print-architecture)
if [ "$arch" == "amd64" ]; then
    for bin in "${KERNEL_BINS[@]}"; do
        cp "$WORKDIR/$KERNEL/$bin" "$RESDIR"
    done
fi
